@ContosoPizza_HostAddress = http://localhost:5047

GET {{ContosoPizza_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{ContosoPizza_HostAddress}}/weatherforecast/1
Accept: application/json

###
POST {{ContosoPizza_HostAddress}}/weatherforecast/
Content-Type: application/json

{
  "date": "2023-05-01",
  "temperatureC": 25,
  "summary": "Hot"
}


###
GET {{ContosoPizza_HostAddress}}/pizza/
Accept: application/json

###
GET {{ContosoPizza_HostAddress}}/pizza/1
Accept: application/json

### 
POST {{ContosoPizza_HostAddress}}/pizza/
Content-Type: application/json

{
  "id": 3,
  "name": "Veggie",
  "isGlutenFree": true
}

###
PUT {{ContosoPizza_HostAddress}}/pizza/3
Content-Type: application/json

{
  "id": 3,
  "name": "Veggie",
  "isGlutenFree": true
}

###
DELETE {{ContosoPizza_HostAddress}}/pizza/3
